### ISSUE TITLE
consider merging fiction/non-fiction into genre (fictionality isn't a thing in literature)

### ISSUE THREAD

**Issue by matthewfdaniels** [jessp/book_covers#38]

**Comment by jessp** [comment]
I'd like to keep it as a separate filter as it's a helpful way of categorizing books that's generally seen as higher up in the hierarchy than genre.

If it's a matter of the wording, we could label the filter "(Non-)fiction" instead (since brevity is important).

Alternatively, we could restyle the genre filter to reflect the hierarchy, i.e.:

Fiction
- Romance
- Historical
Non-fiction
- Biography
- Historical

In this latter case, the question would be how to deal with genres that could be fictional or not.

**Comment by matthewfdaniels** [comment]
Sounds good! Yea let's swap the label. We could also change the third column to be kinda an inferred genre ...see below 
![image](https://user-images.githubusercontent.com/2880174/60180025-1d87e780-97ed-11e9-8bef-a9d32a0e60fa.png)

**Comment by jessp** [comment]
Okay, will go with just swapping the label for now to (Non-)fiction. If it still feels off we can reconsider later.

**Comment by jessp** [comment]
Note: appears as "(Non-)Fiction" due to CSS. I don't think this is an issue though I'd personally prefer "(Non-)fiction." Can change if this is an issue.
