### ISSUE TITLE
center the book on zoom.

### ISSUE THREAD

**Issue by matthewfdaniels** [jessp/book_covers#39]

**Comment by jessp** [comment]
Could you let me know desired appearance?

Current behaviour:

**Desktop**
Book is on left with pop-up to the right so as not to obscure it.

**Mobile**
Book is centered with pop-up appearing in center of book.

Screenshots attached.

<img width="1280" alt="Screen Shot 2019-06-25 at 11 33 29 PM" src="https://user-images.githubusercontent.com/3848662/60135499-23a4a680-97a2-11e9-9722-83da4dd445d9.png">
<img width="277" alt="Screen Shot 2019-06-25 at 11 33 51 PM" src="https://user-images.githubusercontent.com/3848662/60135501-243d3d00-97a2-11e9-98e5-77eaedfb15e4.png">

**Comment by matthewfdaniels** [comment]
this was a comment from the team where they were expecting the zoom to be centered on the book.

**Comment by jessp** [comment]
Understood. I'll consider adding an additional breakpoint for larger screens (>2000px width) where things are more centred. Unless we drop the pop-up with book info (which might be on the table considering issues like #44), I'd prefer to keep the pop-up as non-obscuring as possible.

**Comment by matthewfdaniels** [comment]
You'll see a smaller pop-up in my branch. Let's try a 1000px+ breakpoint if we can.

**Comment by jessp** [comment]
Got it, will do

**Comment by jessp** [comment]
On branch overlayReposition, on screens 900px and wider, books are more centred and less zoomed out (re: #41). Behaviour is otherwise more or less as before. Screenshots attached or you can check out the branch.

<img width="1280" alt="Screen Shot 2019-06-26 at 9 10 08 PM" src="https://user-images.githubusercontent.com/3848662/60207945-63799580-9857-11e9-947b-5af19b823c44.png">
<img width="855" alt="Screen Shot 2019-06-26 at 9 10 33 PM" src="https://user-images.githubusercontent.com/3848662/60207947-63799580-9857-11e9-856e-dda37b0a738d.png">
<img width="322" alt="Screen Shot 2019-06-26 at 9 11 09 PM" src="https://user-images.githubusercontent.com/3848662/60207946-63799580-9857-11e9-981d-9a864b4fa803.png">

**Comment by jessp** [comment]
closed in dda76f5c3e0358a4370a598a23195db88e6ed77e
